name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install uv
        run: pip install uv
      - name: Install dependencies
        run: uv sync --dev --all-extras
      - name: Lint with flake8
        run: uv run flake8 src tests
      - name: Check formatting with black
        run: uv run black --check src tests
      - name: Check imports with isort
        run: uv run isort --check-only src tests
      - name: Run tests
        run: uv run pytest
